# Generated by Django 5.2.8 on 2026-07-20 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Categoría activa')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('descripcion_corta', models.CharField(max_length=220, verbose_name='Descripción corta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción completa')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen principal')),
                ('imagen_url', models.URLField(blank=True, help_text='Opcional. Se utiliza cuando no se carga una imagen local.', verbose_name='URL externa de imagen')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio normal')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio oferta')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('caracteristica_1', models.CharField(max_length=120, verbose_name='Característica 1')),
                ('caracteristica_2', models.CharField(blank=True, max_length=120, verbose_name='Característica 2')),
                ('caracteristica_3', models.CharField(blank=True, max_length=120, verbose_name='Característica 3')),
                ('autonomia_horas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Autonomía en horas')),
                ('bluetooth', models.CharField(blank=True, max_length=30, verbose_name='Versión Bluetooth')),
                ('resistencia_agua', models.CharField(blank=True, max_length=30, verbose_name='Resistencia al agua')),
                ('cancelacion_ruido', models.BooleanField(default=False, verbose_name='Cancelación de ruido')),
                ('destacado', models.BooleanField(default=False, verbose_name='Producto destacado')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto visible')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-destacado', '-creado'],
            },
        ),
    ]
