# Generated by Django 5.2.8 on 2026-07-21 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=20, verbose_name='RUT')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('direccion', models.CharField(max_length=180, verbose_name='Dirección')),
                ('numero_direccion', models.CharField(max_length=20, verbose_name='Número')),
                ('departamento', models.CharField(blank=True, max_length=30, verbose_name='Departamento, casa u oficina')),
                ('referencia', models.CharField(blank=True, max_length=220, verbose_name='Referencia')),
                ('metodo_pago', models.CharField(choices=[('webpay', 'Webpay'), ('transferencia', 'Transferencia bancaria')], default='webpay', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30)),
                ('codigo_descuento', models.CharField(blank=True, max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('despacho', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True, verbose_name='Notas del pedido')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_pedido', to='core.producto')),
            ],
        ),
    ]
