# Generated by Django 5.2.8 on 2026-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_fecha_pago_pedido_mercadopago_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_reservado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
