# Generated by Django 5.2.8 on 2026-07-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_stock_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='correo_confirmacion_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado'), ('revision', 'En revisión')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('webpay', 'Webpay'), ('mercadopago', 'Mercado Pago'), ('transferencia', 'Transferencia bancaria')], default='webpay', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
