# Generated by Django 5.2.8 on 2026-07-26 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pedido_estado_pedidohistorialestado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField(blank=True, default=dict)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_audex', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'carrito de usuario',
                'verbose_name_plural': 'carritos de usuarios',
            },
        ),
    ]
