# Generated by Django 5.2.8 on 2026-07-31 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('confirmacion_pago', 'Confirmación de pago')], max_length=40)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos_enviados', to='core.pedido')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pedido', 'email', 'tipo'), name='correo_unico_por_pedido_email_tipo')],
            },
        ),
    ]
