# Generated by Django 5.2.8 on 2026-07-31 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_correopedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_correo_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='webpay_authorization_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='webpay_buy_order',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='webpay_installments_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='webpay_payment_type_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='webpay_response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='webpay_token',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='webpay_transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='correo_confirmacion_enviado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Correo electrónico del checkout'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('webpay', 'Webpay'), ('mercadopago', 'Mercado Pago'), ('transferencia', 'Transferencia bancaria')], db_index=True, default='webpay', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='stock_descontado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pedidohistorialestado',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='pedidohistorialestado',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pedidohistorialestado',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente de pago'), ('confirmado', 'Pago confirmado'), ('preparacion', 'En preparación'), ('listo', 'Listo para despacho'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='', max_length=30, verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='pedidohistorialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('confirmado', 'Pago confirmado'), ('preparacion', 'En preparación'), ('listo', 'Listo para despacho'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, max_length=30, verbose_name='Estado nuevo'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pago', 'creado'], name='pedido_pago_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['metodo_pago', 'estado_pago'], name='pedido_metodo_pago_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidohistorialestado',
            index=models.Index(fields=['pedido', 'creado'], name='historial_pedido_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidohistorialestado',
            index=models.Index(fields=['pedido', 'estado_nuevo'], name='historial_pedido_estado_idx'),
        ),
    ]
