# Generated by Django 5.2.8 on 2026-08-02 06:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pedido_fecha_correo_confirmacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El código solo puede contener letras, números, guiones y guiones bajos.', regex='^[A-Z0-9_-]+$')])),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('monto_minimo_compra', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('usado', 'Utilizado'), ('anulado', 'Anulado')], db_index=True, default='disponible', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vence_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reservado_en', models.DateTimeField(blank=True, null=True)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Código de descuento de cliente',
                'verbose_name_plural': 'Códigos de descuento de clientes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionDescuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_activo', models.BooleanField(default=False, verbose_name='Activar descuento general')),
                ('general_codigo', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='El código solo puede contener letras, números, guiones y guiones bajos.', regex='^[A-Z0-9_-]+$')], verbose_name='Código general')),
                ('general_porcentaje', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje general')),
                ('general_monto_minimo', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Compra mínima general')),
                ('fidelidad_activa', models.BooleanField(default=False, verbose_name='Activar premios de fidelidad')),
                ('fidelidad_monto_objetivo', models.DecimalField(decimal_places=0, default=100000, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto para ganar un premio')),
                ('fidelidad_porcentaje', models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje del premio')),
                ('fidelidad_monto_minimo_compra', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Compra mínima para usar el premio')),
                ('fidelidad_vigencia_dias', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(730)], verbose_name='Vigencia del premio en días')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de descuentos',
                'verbose_name_plural': 'Configuración de descuentos',
            },
        ),
        migrations.CreateModel(
            name='SaldoFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_historico', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('premios_generados', models.PositiveIntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo de fidelidad',
                'verbose_name_plural': 'Saldos de fidelidad',
                'ordering': ['-saldo_actual'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='fidelidad_contabilizada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_descuento',
            field=models.CharField(choices=[('ninguno', 'Sin descuento'), ('general', 'Código general'), ('fidelidad', 'Premio de fidelidad')], db_index=True, default='ninguno', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_descuento',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['tipo_descuento', 'creado'], name='pedido_desc_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', 'fidelidad_contabilizada'], name='pedido_fidelidad_idx'),
        ),
        migrations.AddField(
            model_name='codigodescuentocliente',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigo_fidelidad', to='core.pedido'),
        ),
        migrations.AddField(
            model_name='codigodescuentocliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_descuento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuraciondescuentos',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_descuentos_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saldofidelidad',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_fidelidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='codigodescuentocliente',
            index=models.Index(fields=['estado', 'vence_en'], name='codigo_desc_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='codigodescuentocliente',
            index=models.Index(fields=['usuario', 'estado'], name='codigo_desc_usuario_idx'),
        ),
        migrations.AddConstraint(
            model_name='codigodescuentocliente',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje__gt', 0)), name='cod_desc_pct_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='codigodescuentocliente',
            constraint=models.CheckConstraint(condition=models.Q(('monto_minimo_compra__gte', 0)), name='cod_desc_min_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='saldofidelidad',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_actual__gte', 0)), name='saldo_fid_actual_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='saldofidelidad',
            constraint=models.CheckConstraint(condition=models.Q(('total_historico__gte', 0)), name='saldo_fid_total_gte_0'),
        ),
    ]
