# Generated by Django 5.2.8 on 2026-08-02 09:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_codigodescuentocliente_configuraciondescuentos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'Código general'), ('fidelidad', 'Premio de fidelidad')], db_index=True, default='general', max_length=20)),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre interno')),
                ('codigo', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='El código solo puede contener letras, números, guiones y guiones bajos.', regex='^[A-Z0-9_-]+$')])),
                ('descripcion', models.CharField(blank=True, max_length=220)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('consumido', models.BooleanField(db_index=True, default=False, help_text='Solo se utiliza para premios personales de fidelidad.')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('monto_minimo', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_maximo_descuento', models.DecimalField(blank=True, decimal_places=0, help_text='Opcional. Limita el monto máximo que puede descontar este código.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('fecha_inicio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('numero_meta', models.PositiveIntegerField(blank=True, help_text='Número de meta que originó el premio personal.', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Código de descuento',
                'verbose_name_plural': 'Códigos de descuento',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=False, verbose_name='Activar programa de fidelidad')),
                ('monto_objetivo', models.DecimalField(decimal_places=0, default=100000, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Monto para cumplir una meta')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje del premio')),
                ('monto_minimo_compra', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Compra mínima para utilizar el premio')),
                ('monto_maximo_descuento', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Descuento máximo del premio')),
                ('vigencia_dias', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(730)], verbose_name='Vigencia del código en días')),
                ('prefijo_codigo', models.CharField(default='AUDEXFIEL', help_text='Ejemplo: AUDEXFIEL. El sistema agregará el usuario, la meta y un fragmento aleatorio.', max_length=24, validators=[django.core.validators.RegexValidator(message='El código solo puede contener letras, números, guiones y guiones bajos.', regex='^[A-Z0-9_-]+$')], verbose_name='Prefijo de los códigos de premio')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de fidelidad',
                'verbose_name_plural': 'Configuración de fidelidad',
            },
        ),
        migrations.CreateModel(
            name='UsoCodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_clave', models.CharField(db_index=True, help_text='Identificador HMAC generado a partir del RUT normalizado.', max_length=80)),
                ('rut_enmascarado', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('liberado', 'Liberado')], db_index=True, default='reservado', max_length=20)),
                ('subtotal_original', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('descuento_aplicado', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_final', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('reservado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('liberado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Uso de código de descuento',
                'verbose_name_plural': 'Usos de códigos de descuento',
                'ordering': ['-reservado_en'],
            },
        ),
        migrations.RemoveField(
            model_name='codigodescuentocliente',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='codigodescuentocliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='configuraciondescuentos',
            name='actualizado_por',
        ),
        migrations.AlterModelOptions(
            name='correopedido',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'ordering': ['pk'], 'verbose_name': 'Ítem de pedido', 'verbose_name_plural': 'Ítems de pedido'},
        ),
        migrations.RenameField(
            model_name='saldofidelidad',
            old_name='premios_generados',
            new_name='metas_cumplidas',
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='descuento_codigo',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Parte proporcional del cupón asignada a esta línea.', max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='descuento_producto_unitario',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Descuento propio de la oferta del producto por unidad.', max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='precio_lista_unitario',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio normal del producto al momento de la compra.', max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='total_final',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total de la línea después del código de descuento.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_descuento',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rut',
            field=models.CharField(db_index=True, max_length=20, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='total',
            field=models.DecimalField(decimal_places=0, help_text='Total de la línea antes del código de descuento.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_reservado',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock reservado'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='pedido_item_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='pedido_item_precio_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='pedido_item_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_codigo__gte', 0)), name='pedido_item_desc_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_final__gte', 0)), name='pedido_item_final_gte_0'),
        ),
        migrations.AddField(
            model_name='codigodescuento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_descuento_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codigodescuento',
            name='usuario_exclusivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_descuento_exclusivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_descuento_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='core.codigodescuento', verbose_name='Código de descuento aplicado'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='pedido_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0)), name='pedido_descuento_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('despacho__gte', 0)), name='pedido_despacho_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='pedido_total_gte_0'),
        ),
        migrations.AddField(
            model_name='configuracionfidelidad',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_fidelidad_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usocodigodescuento',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='core.codigodescuento'),
        ),
        migrations.AddField(
            model_name='usocodigodescuento',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uso_codigo_descuento', to='core.pedido'),
        ),
        migrations.AddField(
            model_name='usocodigodescuento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_codigos_descuento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CodigoDescuentoCliente',
        ),
        migrations.DeleteModel(
            name='ConfiguracionDescuentos',
        ),
        migrations.AddIndex(
            model_name='codigodescuento',
            index=models.Index(fields=['tipo', 'activo'], name='codigo_tipo_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='codigodescuento',
            index=models.Index(fields=['usuario_exclusivo', 'consumido'], name='codigo_usuario_consum_idx'),
        ),
        migrations.AddIndex(
            model_name='codigodescuento',
            index=models.Index(fields=['activo', 'fecha_inicio', 'fecha_fin'], name='codigo_vigencia_idx'),
        ),
        migrations.AddConstraint(
            model_name='codigodescuento',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje__gt', 0)), name='codigo_pct_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='codigodescuento',
            constraint=models.CheckConstraint(condition=models.Q(('monto_minimo__gte', 0)), name='codigo_min_gte_0'),
        ),
        migrations.AddIndex(
            model_name='usocodigodescuento',
            index=models.Index(fields=['codigo', 'estado'], name='uso_codigo_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='usocodigodescuento',
            index=models.Index(fields=['cliente_clave', 'estado'], name='uso_cliente_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='usocodigodescuento',
            index=models.Index(fields=['confirmado_en'], name='uso_confirmado_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='usocodigodescuento',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['reservado', 'confirmado'])), fields=('codigo', 'cliente_clave'), name='codigo_un_uso_por_cliente'),
        ),
        migrations.AddConstraint(
            model_name='usocodigodescuento',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_original__gte', 0)), name='uso_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='usocodigodescuento',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_aplicado__gte', 0)), name='uso_descuento_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='usocodigodescuento',
            constraint=models.CheckConstraint(condition=models.Q(('total_final__gte', 0)), name='uso_total_gte_0'),
        ),
    ]
