# Generated by Django 5.2.8 on 2026-08-05 23:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_codigodescuento_configuracionfidelidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='codigodescuento',
            name='codigo_pct_gt_0',
        ),
        migrations.AddField(
            model_name='codigodescuento',
            name='modalidad',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo en CLP')], db_index=True, default='porcentaje', help_text='Selecciona si el código descontará un porcentaje o un monto fijo en CLP.', max_length=20, verbose_name='Modalidad del descuento'),
        ),
        migrations.AddField(
            model_name='codigodescuento',
            name='monto_descuento',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Completar solamente cuando la modalidad sea monto fijo en CLP. Ejemplo: 38000.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Monto fijo de descuento'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Código activo'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='codigo',
            field=models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='El código solo puede contener letras, números, guiones y guiones bajos.', regex='^[A-Z0-9_-]+$')], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='consumido',
            field=models.BooleanField(db_index=True, default=False, help_text='Solo se utiliza para premios personales de fidelidad.', verbose_name='Código consumido'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_descuento_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=220, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='monto_maximo_descuento',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Opcional. Solo se utiliza en descuentos porcentuales para limitar el monto máximo que puede descontarse.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Descuento máximo'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Subtotal mínimo que debe alcanzar el cliente para utilizar este código.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Compra mínima'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='numero_meta',
            field=models.PositiveIntegerField(blank=True, help_text='Número de meta que originó el premio personal.', null=True, verbose_name='Número de meta'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Completar solamente cuando la modalidad sea porcentaje. Ejemplo: 15 para un 15%.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='tipo',
            field=models.CharField(choices=[('general', 'Código general'), ('fidelidad', 'Premio de fidelidad')], db_index=True, default='general', max_length=20, verbose_name='Tipo de código'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='usuario_exclusivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_descuento_exclusivos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario exclusivo'),
        ),
        migrations.AddIndex(
            model_name='codigodescuento',
            index=models.Index(fields=['modalidad', 'activo'], name='codigo_modal_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='codigodescuento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('modalidad', 'porcentaje'), ('monto_descuento__isnull', True), ('porcentaje__gt', 0)), models.Q(('modalidad', 'monto_fijo'), ('monto_descuento__gt', 0), ('porcentaje__isnull', True)), _connector='OR'), name='codigo_modalidad_valida'),
        ),
    ]
