# Generated by Django 5.2.8 on 2026-08-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_codigodescuento_codigo_pct_gt_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigodescuento',
            name='tipo',
            field=models.CharField(choices=[('general', 'Código general'), ('especial', 'Oferta especial para usuario'), ('fidelidad', 'Premio de fidelidad')], db_index=True, default='general', max_length=20, verbose_name='Tipo de código'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_descuento',
            field=models.CharField(choices=[('ninguno', 'Sin descuento'), ('general', 'Código general'), ('especial', 'Oferta especial para usuario'), ('fidelidad', 'Premio de fidelidad')], db_index=True, default='ninguno', max_length=20),
        ),
    ]
