# Generated by Django 5.2.8 on 2026-08-07 03:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_codigodescuento_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de la meta')),
                ('activa', models.BooleanField(db_index=True, default=True, verbose_name='Meta activa')),
                ('monto_objetivo', models.DecimalField(db_index=True, decimal_places=0, help_text='Ejemplo: 100000 significa que el cliente debe acumular $100.000 en compras aprobadas.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Monto acumulado necesario')),
                ('modalidad', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo en CLP')], max_length=20, verbose_name='Tipo de premio')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje del premio')),
                ('monto_descuento', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Monto del premio en CLP')),
                ('monto_minimo_compra', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Compra mínima para utilizar el premio')),
                ('monto_maximo_descuento', models.DecimalField(blank=True, decimal_places=0, help_text='Solo se utiliza para premios porcentuales.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Descuento máximo')),
                ('vigencia_dias', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(730)], verbose_name='Vigencia del premio en días')),
                ('prefijo_codigo', models.CharField(default='AUDEXFIEL', max_length=24, validators=[django.core.validators.RegexValidator(message='El código solo puede contener letras, números, guiones y guiones bajos.', regex='^[A-Z0-9_-]+$')], verbose_name='Prefijo del código')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden de la meta')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta de fidelidad',
                'verbose_name_plural': 'Metas de fidelidad',
                'ordering': ['monto_objetivo', 'orden'],
            },
        ),
        migrations.RemoveField(
            model_name='configuracionfidelidad',
            name='actualizado_por',
        ),
        migrations.AlterModelOptions(
            name='saldofidelidad',
            options={'ordering': ['-total_historico']},
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='consumido',
            field=models.BooleanField(db_index=True, default=False, help_text='Se utiliza en premios personales de fidelidad de un solo uso.', verbose_name='Código consumido'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='modalidad',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo en CLP')], db_index=True, default='porcentaje', max_length=20, verbose_name='Modalidad del descuento'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='monto_descuento',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Monto fijo de descuento'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='monto_maximo_descuento',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Descuento máximo'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Compra mínima'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='numero_meta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de meta'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='tipo',
            field=models.CharField(choices=[('general', 'Código general'), ('fidelidad', 'Premio de fidelidad')], db_index=True, default='general', max_length=20, verbose_name='Tipo de código'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='usuario_exclusivo',
            field=models.ForeignKey(blank=True, help_text='Se completa automáticamente para premios de fidelidad.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_descuento_exclusivos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario'),
        ),
        migrations.AlterField(
            model_name='saldofidelidad',
            name='total_historico',
            field=models.DecimalField(db_index=True, decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='usocodigodescuento',
            name='cliente_clave',
            field=models.CharField(db_index=True, help_text='Identificador único del cliente. Para usuarios autenticados utiliza USER:<id>. Para invitados utiliza un HMAC del RUT normalizado.', max_length=80),
        ),
        migrations.AddIndex(
            model_name='usocodigodescuento',
            index=models.Index(fields=['usuario', 'estado'], name='uso_usuario_estado_idx'),
        ),
        migrations.AddField(
            model_name='metafidelidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_fidelidad_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codigodescuento',
            name='meta_fidelidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_generados', to='core.metafidelidad', verbose_name='Meta de fidelidad'),
        ),
        migrations.AddIndex(
            model_name='codigodescuento',
            index=models.Index(fields=['meta_fidelidad', 'usuario_exclusivo'], name='codigo_meta_usuario_idx'),
        ),
        migrations.AddConstraint(
            model_name='codigodescuento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('modalidad', 'monto_fijo'), _negated=True), ('monto_minimo__gt', 0), _connector='OR'), name='codigo_fijo_min_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='codigodescuento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('meta_fidelidad__isnull', True), ('tipo', 'general'), ('usuario_exclusivo__isnull', True)), models.Q(('meta_fidelidad__isnull', False), ('tipo', 'fidelidad'), ('usuario_exclusivo__isnull', False)), _connector='OR'), name='codigo_propietario_valido'),
        ),
        migrations.AddConstraint(
            model_name='codigodescuento',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'fidelidad')), fields=('usuario_exclusivo', 'meta_fidelidad'), name='fidelidad_una_meta_por_usuario'),
        ),
        migrations.DeleteModel(
            name='ConfiguracionFidelidad',
        ),
        migrations.AddConstraint(
            model_name='metafidelidad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('modalidad', 'porcentaje'), ('monto_descuento__isnull', True), ('porcentaje__gt', 0)), models.Q(('modalidad', 'monto_fijo'), ('monto_descuento__gt', 0), ('porcentaje__isnull', True)), _connector='OR'), name='meta_fidelidad_modalidad_valida'),
        ),
        migrations.AddConstraint(
            model_name='metafidelidad',
            constraint=models.CheckConstraint(condition=models.Q(('monto_objetivo__gt', 0)), name='meta_fidelidad_objetivo_gt_0'),
        ),
    ]
