# Generated by Django 5.2.8 on 2026-08-11 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_metafidelidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bsale_client_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID cliente Bsale'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bsale_document_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID documento Bsale'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bsale_emitido',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Boleta Bsale emitida'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bsale_emitido_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha emisión Bsale'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bsale_folio',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Folio Bsale'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bsale_token_documento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Token documento Bsale'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bsale_ultimo_error',
            field=models.TextField(blank=True, verbose_name='Último error Bsale'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bsale_url_pdf',
            field=models.URLField(blank=True, max_length=500, verbose_name='PDF Bsale'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bsale_url_publica',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL pública Bsale'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bsale_url_xml',
            field=models.URLField(blank=True, max_length=500, verbose_name='XML Bsale'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['bsale_emitido', 'creado'], name='pedido_bsale_emitido_idx'),
        ),
    ]
