# Generated by Django 5.2.8 on 2026-08-22 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pedido_bsale_client_id_pedido_bsale_document_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/principales/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Opcional. Se utiliza cuando no se carga una imagen principal local.', verbose_name='URL externa de imagen principal'),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/', verbose_name='Imagen')),
                ('texto_alt', models.CharField(blank=True, help_text='Descripción breve de la imagen. Ayuda con accesibilidad y SEO.', max_length=180, verbose_name='Texto alternativo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Define el orden de aparición. 0 se muestra primero.', verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
