# Generated by Django 5.2.8 on 2026-08-24 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_producto_imagen_alter_producto_imagen_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_bsale_emitido_idx',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_client_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_document_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_emitido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_emitido_en',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_folio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_token_documento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_ultimo_error',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_url_pdf',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_url_publica',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bsale_url_xml',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nubox_comuna_codigo',
            field=models.CharField(blank=True, help_text='Código territorial de comuna utilizado para emitir DTE en Nubox.', max_length=5, verbose_name='Código comuna Nubox/SII'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nubox_document_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID documento Nubox'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nubox_emitido',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Boleta Nubox emitida'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nubox_emitido_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha emisión Nubox'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nubox_estado',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Estado documento Nubox'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nubox_folio',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Folio Nubox'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nubox_idempotence_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='ID de idempotencia Nubox'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nubox_region_codigo',
            field=models.CharField(blank=True, help_text='Código territorial de región utilizado para emitir DTE en Nubox.', max_length=2, verbose_name='Código región Nubox/SII'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nubox_ultimo_error',
            field=models.TextField(blank=True, verbose_name='Último error Nubox'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['nubox_emitido', 'creado'], name='pedido_nubox_emitido_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['nubox_estado', 'creado'], name='pedido_nubox_estado_idx'),
        ),
    ]
