# Generated by Django 5.2.8 on 2026-09-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_pedido_pedido_bsale_emitido_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla_envio_minima',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='', help_text='Opcional. Déjalo vacío para utilizar el cálculo automático según la cantidad de productos del carrito. Selecciona XS, S, M o L si este producto requiere un paquete mínimo específico.', max_length=2, verbose_name='Talla mínima de envío'),
        ),
        migrations.CreateModel(
            name='TarifaBlueExpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('SANTIAGO', 'Santiago'), ('CENTRO', 'Zona centro'), ('EXTREMO', 'Zona extrema')], db_index=True, max_length=20, verbose_name='Zona')),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], db_index=True, max_length=2, verbose_name='Talla')),
                ('precio', models.PositiveIntegerField(help_text='Valor del despacho en pesos chilenos.', verbose_name='Precio de envío')),
                ('activa', models.BooleanField(db_index=True, default=True, verbose_name='Tarifa activa')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa Blue Express',
                'verbose_name_plural': 'Tarifas Blue Express',
                'ordering': ['zona', 'talla'],
                'constraints': [models.UniqueConstraint(fields=('zona', 'talla'), name='blueexpress_zona_talla_unica')],
            },
        ),
    ]
