# Generated by Django 5.2.8 on 2026-09-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_producto_talla_envio_minima_tarifablueexpress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla_envio_minima',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='', help_text='Configuración administrativa. Déjalo vacío para utilizar el cálculo automático según la cantidad del carrito.', max_length=2, verbose_name='Talla mínima de envío'),
        ),
    ]
