# Generated by Django 5.2.8 on 2026-09-06 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_producto_talla_envio_minima'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaEnvioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_desde', models.PositiveSmallIntegerField(help_text='Cantidad mínima de unidades de este producto para aplicar la regla.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Cantidad desde')),
                ('cantidad_hasta', models.PositiveSmallIntegerField(help_text='Cantidad máxima de unidades de este producto para aplicar la regla.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Cantidad hasta')),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=2, verbose_name='Talla de envío')),
                ('activa', models.BooleanField(db_index=True, default=True, verbose_name='Regla activa')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_envio', to='core.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Regla especial de envío',
                'verbose_name_plural': 'Reglas especiales de envío',
                'ordering': ['producto', 'cantidad_desde', 'cantidad_hasta'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_hasta__gte', models.F('cantidad_desde'))), name='regla_envio_rango_valido'), models.UniqueConstraint(fields=('producto', 'cantidad_desde', 'cantidad_hasta'), name='regla_envio_producto_rango_unico')],
            },
        ),
    ]
