# Generated by Django 5.2.8 on 2026-09-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_reglaenvioproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='ID público'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla_envio_minima',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='', help_text='Configuración administrativa heredada. La lógica nueva utiliza reglas especiales de envío por cantidad.', max_length=2, verbose_name='Talla mínima de envío'),
        ),
    ]
