# Generated by Django 5.2.8 on 2026-09-08 04:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_poblar_public_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID público'),
        ),
    ]
