# Generated by Django 5.2.8 on 2026-09-08 22:45

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_producto_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoResena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField(db_index=True, help_text='Valoración entre 1 y 5 estrellas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Valoración')),
                ('comentario', models.TextField(help_text='Máximo 2.000 caracteres.', max_length=2000, verbose_name='Comentario')),
                ('compra_verificada', models.BooleanField(db_index=True, default=False, editable=False, help_text='Se calcula automáticamente a partir de los pedidos pagados.', verbose_name='Compra verificada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], db_index=True, default='aprobada', max_length=12, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_productos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña de producto',
                'verbose_name_plural': 'Reseñas de productos',
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResenaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='JPG, JPEG, PNG o WEBP. Máximo 5 MB.', upload_to=core.models.ruta_imagen_resena, validators=[core.models.validar_imagen_resena], verbose_name='Imagen')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.productoresena', verbose_name='Reseña')),
            ],
            options={
                'verbose_name': 'Imagen de reseña',
                'verbose_name_plural': 'Imágenes de reseñas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResenaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(help_text='Máximo 1.500 caracteres.', max_length=1500, verbose_name='Respuesta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], db_index=True, default='aprobada', max_length=12, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.productoresena', verbose_name='Reseña')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_resenas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta a reseña',
                'verbose_name_plural': 'Respuestas a reseñas',
                'ordering': ['creado', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productoresena',
            index=models.Index(fields=['producto', 'estado', 'creado'], name='resena_prod_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='productoresena',
            index=models.Index(fields=['usuario', 'creado'], name='resena_usuario_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoresena',
            constraint=models.UniqueConstraint(fields=('producto', 'usuario'), name='resena_usuario_producto_unica'),
        ),
        migrations.AddConstraint(
            model_name='productoresena',
            constraint=models.CheckConstraint(condition=models.Q(('estrellas__gte', 1), ('estrellas__lte', 5)), name='resena_estrellas_1_5'),
        ),
        migrations.AddIndex(
            model_name='resenaimagen',
            index=models.Index(fields=['resena', 'orden'], name='resena_imagen_orden_idx'),
        ),
        migrations.AddIndex(
            model_name='resenarespuesta',
            index=models.Index(fields=['resena', 'estado', 'creado'], name='respuesta_resena_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='resenarespuesta',
            index=models.Index(fields=['usuario', 'creado'], name='respuesta_usuario_fecha_idx'),
        ),
    ]
