# Generated by Django 5.2.8 on 2026-09-10 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_productoresena_resenaimagen_resenarespuesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('webpay', 'Webpay / Transbank'), ('mercadopago', 'Mercado Pago')], db_index=True, max_length=30)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado'), ('reembolsado', 'Reembolsado')], db_index=True, default='pendiente', max_length=20)),
                ('estado_proveedor', models.CharField(blank=True, max_length=50)),
                ('id_transaccion', models.CharField(blank=True, db_index=True, max_length=100)),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=100)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=100)),
                ('tipo_pago', models.CharField(blank=True, max_length=100)),
                ('ultimos_4', models.CharField(blank=True, max_length=4)),
                ('cuotas', models.PositiveIntegerField(default=0)),
                ('datos_respaldo', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_pago', to='core.pedido')),
            ],
            options={
                'verbose_name': 'Comprobante de pago',
                'verbose_name_plural': 'Comprobantes de pago',
                'ordering': ['-creado'],
            },
        ),
    ]
