# Generated by Django 5.2.8 on 2026-09-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_comprobantepago'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_nubox_emitido_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_nubox_estado_idx',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nubox_comuna_codigo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nubox_document_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nubox_emitido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nubox_emitido_en',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nubox_estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nubox_folio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nubox_idempotence_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nubox_region_codigo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nubox_ultimo_error',
        ),
        migrations.AddField(
            model_name='pedido',
            name='correo_despacho_enviado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='correo_entrega_enviado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_correo_despacho',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_correo_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
