# Generated by Django 5.2.8 on 2026-10-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_pedido_pedido_nubox_emitido_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_seguimiento',
            field=models.CharField(blank=True, db_index=True, help_text='Número de OS o seguimiento entregado por el transportista.', max_length=100, verbose_name='Número de seguimiento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportista',
            field=models.CharField(blank=True, choices=[('bluexpress', 'Blue Express')], db_index=True, max_length=30, verbose_name='Transportista'),
        ),
    ]
